### ISSUE TITLE
error occurs during installation

### ISSUE THREAD

**Issue by MachineGUN001** [PatWalters/useful_rdkit_utils#1]
hi,

my system is win10, 64-bit

ERROR: Could not install packages due to an OSError: [WinError 5] \u62d2\u7edd\u8bbf\u95ee\u3002: 'C:\\Users\\lenovo\\anaconda3\\Lib\\site-packages\\rdkit\\rdBase.pyd'
Consider using the `--user` option or check the permissions.

could you please give some comments or suggestions to fix it ?
that error leads to the failure of installation. 
many thanks,

**Comment by PatWalters** [comment]
It appears that you don't have permission to write into the site-packages directory.  You may want to try
pip install  --user useful_rdkit_utils
For more information, check out this link 
https://stackoverflow.com/questions/51912999/could-not-install-packages-due-to-an-environmenterror-winerror-5-access-is-de

**Comment by MachineGUN001** [comment]
> Owner

appreciate your helps so much. following your method to try `pip install --user useful_rdkit_utils`, that looks works well. 

`Installing collected packages: rdkit-pypi, useful-rdkit-utils
Successfully installed rdkit-pypi-2021.9.4 useful-rdkit-utils-0.1.4`

however, when i try to run demo ipynb file of useful-rdkit-utils, and try to import useful_rdkit_utils as uru, the erros came out, **ImportError: DLL load failed while importing rdBase:** .

could you please give some suggestions about that to fix issues? many thanks,

**Comment by MachineGUN001** [comment]
![Snipaste_2022-01-15_21-42-39](https://user-images.githubusercontent.com/16698635/149624245-2914df1c-c1c3-4e48-9570-217eee8ca968.png)

after running the command line `pip install --user useful_rdkit_utils`, the rdkit cannot be imported correctly.
eg from rdkit.Chem import Draw. that looks there are some errors .

installation of rdkit is still a headache for me. could you please provide some suggestions how to fix it?
many thanks,

**Comment by PatWalters** [comment]
Make sure the version Jupyter you're using is in the same conda environment that you installed useful_rdkit_utils into.   Make sure you can load the RDKit from the python shell without Jupyter.  Try starting python, then typing
from rdkit import Chem

**Comment by PatWalters** [comment]
I'm going to consider this one closed

**Comment by MachineGUN001** [comment]
> I'm going to consider this one closed

yep. appreciate your kind and nice hleps. after re-installating rdkit, this issue is done, as well as this function works well. thanks a lot.
