### ISSUE TITLE
SMARTS Pattern for Exocyclic Double Bonds in ring_systems.py

### ISSUE THREAD

**Issue by XinhaoLi74** [PatWalters/useful_rdkit_utils#25]
Hi Pat,

I noticed a potential error in the SMARTS pattern used to identify exocyclic double bonds in ring_systems.py. Specifically, in the following snippet:

    def __init__(self):
        """Initialize susbstructure search objects to identify key functionality
        """
        self.ring_db_pat = Chem.MolFromSmarts("[#6R,#18R]=[OR0,SR0,CR0,NR0]")
        self.ring_atom_pat = Chem.MolFromSmarts("[R]")

It looks like #18R (representing a noble gas, argon) should actually be #16R (for sulfur in a ring). Using #18R seems incorrect here, as argon doesn’t typically participate in bonding.

Thanks.

**Comment by PatWalters** [comment]
Thanks for reporting this.  I'm sorry it took me so long to see it.  I've fixed the bug.

**Comment by PatWalters** [comment]
Closed
