### ISSUE TITLE
Demo_cross_validate notebook has different number of cross_validate parameters compared to split_utils.py file

### ISSUE THREAD

**Issue by henkjanvanmanen** [PatWalters/useful_rdkit_utils#26]
Hi, as someone quite new in cheminformatics I like the Practical Cheminformatics blog and associated Jupyter notebooks a lot!
I'd like to try the notebook **"demo_cross_validate.ipynb"** and I noticed that in this notebook the cross_validate function has, among others, **descriptor_list** and **metric_list** as parameters. However, when I install useful_rdkit_utils (using pip) and import the cross_validate function, it seems that another version is used that does not have the descriptor_list and metric_list parameters. The **split_utils.py** file on the Github site indeed contains the version without these parameters. How can I get access to the cross_validate function from the "demo_cross_validate.ipynb" notebook so I can try to run this notebook with my own data?
Thanks!

**Comment by PatWalters** [comment]
Sorry about that.   I updated and simplified the cross_validate method but neglected to update the notebook. This has been fixed and the notebook is in sync wit the method.

**Comment by PatWalters** [comment]
Notebook was updated
